### ISSUE TITLE
$start_text keeps getting send

### ISSUE THREAD

**Issue by puertajulian** [schmidtflo/telegram_bot_blog#1]
After setting this up $start_text keeps getting send to me as suscriber forever every 2 seconds. I had to revoke the api with @BotFather or change the bot.php to something else to stop it.

**Comment by schmidtflo** [comment]
That's strange. Did you enable the logging? And what is logged?

**Comment by puertajulian** [comment]
Yes logging is enabled. This is part of 55781 lines it creates (lol).

06.07.2015 13:26:27 /start  //  puerta
06.07.2015 13:26:29 /start  //  puerta
06.07.2015 13:26:31 /start  //  puerta
06.07.2015 13:26:33 /start  //  puerta
06.07.2015 13:26:35 /start  //  puerta
06.07.2015 13:26:37 /start  //  puerta
06.07.2015 13:26:39 /start  //  puerta

**Comment by puertajulian** [comment]
Also I just notice that revoking the token stops the script for sending the $start_text message but does not stop the call to the bot itself.

**Comment by schmidtflo** [comment]
Seems like the Telegram API is calling your script, but don't get an answer that it was successful and tries it 2 seconds later again.

**Comment by puertajulian** [comment]
Yes something like this. Had to remove the bot and recreated it as it wont let him recive any other info for other hook.
